# Special syscalls for Hotpot
#
# It is *NOT* a good idea to add extra syscalls to
# support customized features. It will be better to
# reuse current /proc or syscalls.
#
# Anyway, lesson learned.

obj-y := syscall.o
