# page_fault_latency.script

reset

set border 3

set output "pf-latency.png"
set style data histograms
set style fill solid 1.00 border -1

set ylabel "Latency (usec)" font "Times-Roman, 25"
set yrange [0:10]
set ytics 2

set xtics nomirror font "Times-Roman, 25"
set ytics nomirror font "Times-Roman, 25"

set key center bottom outside horizontal enhanced
set key spacing 1 samplen 2 width 0 height 0
set key font "Times-Roman, 20"

plot "page_fault_latency.data" \
using 2:xtic(1) title "Anonymous" lc rgb "#000000", \
'' using 3 title "File-Backed" lc rgb "#4c4c4c", \
'' using 4 title "Local-DSNVM" lc rgb "#999999", \
'' using 5 title "Remote-DSNVM" lc rgb "#e5e5e5"
